# Generated by Django 3.2 on 2021-05-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210430_1321'),
        ('users', '0002_profile_moneys'),
    ]

    operations = [
    ]
