# Generated by Django 2.2.5 on 2021-05-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210520_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='moneys',
        ),
    ]
