# Generated by Django 2.2.5 on 2021-05-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_moneys'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moneys',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=6),
        ),
    ]
