# Generated by Django 3.2 on 2021-05-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210430_1321'),
        ('blog', '0004_comment'),
    ]

    operations = [
    ]
